# Задачи на повторение пройденного материала

### Задача 1

Даны четыре действительных числа: x1, y1, x2, y2. Напишите функцию distance(x1, y1, x2, y2), вычисляющая евклидово расстояние ( https://ru.wikipedia.org/wiki/%D0%95%D0%B2%D0%BA%D0%BB%D0%B8%D0%B4%D0%BE%D0%B2%D0%B0_%D0%BC%D0%B5%D1%82%D1%80%D0%B8%D0%BA%D0%B0 ) между точкой (x1,y1) и (x2,y2).

In [1]:
from math import sqrt

x1 = float(input())
y1 = float(input())
x2 = float(input())
y2 = float(input())

def distance(x1, y1, x2, y2):
    return sqrt((x1-x2)**2 + (y1-y2)**2)
print(distance(x1, y1, x2, y2))

3
4
5
6
2.8284271247461903


### Задача 2

Написать функцию season(month), принимающую 1 аргумент — номер месяца (от 1 до 12), которая присваивает глобальной переменной s время года, которому этот месяц принадлежит (зима, весна, лето или осень).

In [2]:
time_of_year = ""
print("enter a month")
month = int(input())
def season(month):
    if month in (1,2,12):
        return "winter"
    elif month in (3,4,5):
        return "spring"
    elif month in (6,7,8):
        return "summer"
    elif month in (9,10,11):
        return "fall"
    else:
        return "error"
print(season(month))

enter a month
5
spring


### Задача 3

Написать функцию is_prime, принимающую 1 аргумент — число от 0 до 1000, и возвращающую True, если оно простое, и False - иначе.

In [3]:
from math import sqrt
print("enter a number from 0 to 1000")
number = int(input())
def is_prime(number):
    for i in range(2, int(sqrt(number)+1)):
        if number % i == 0:
            return False
    return True
print(is_prime(number))

enter a number from 0 to 1000
7
True


### Задача 4

Написать функцию reverse_list(lst), которая принимает в качестве аргумента список и возвращаем его в перевернутом виде.

Например,
* исходный список: 8, 1, 0, 4
* полученный список: 4, 0, 1, 8
Использовать встроенные функции Python нельзя.

In [4]:
lst = [1,2,3,4,5,6,7]
def reverse_list(lst):
    return lst[::-1]
print(reverse_list(lst))

[7, 6, 5, 4, 3, 2, 1]


### Задача 5

Распечатайте с 4 по 8 символ фразы "Привет мир!" приведенные к верхнему регистру.

In [5]:
stroka = "Привет, мир"
new_stroka = ''
for i, s in enumerate(stroka):
    if i >= 4 and i <= 8:
        new_stroka += s.upper()
    else:
        new_stroka += s
print(new_stroka)

ПривЕТ, Мир


### Задача 6

Напишите код, который все элементы массива x с нечетными индексами переставит в обратном порядке.

Т.е. если x = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], то код должен получать [0, 9, 2, 7, 4, 5, 6, 3, 8, 1]

In [6]:
array = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
array[1::2] = array[1::2][::-1]
print(array)


[0, 9, 2, 7, 4, 5, 6, 3, 8, 1]


### Задача 7

Напишите цикл, который выводит все числа от 0 до 500, делящиеся на 7, если в них есть цифра 8.

In [7]:
for number in range(0, 501):
    if number % 7 == 0:
        number_str = set(str(number))
        if '8' in number_str:
            print(number)

28
84
98
168
182
189
238
280
287
308
378
385
448
483


### Задача 8

На вход функция more_than_five(lst) получает список из целых чисел. Результатом работы функции должен стать новый список, в котором содержатся только те числа, которые больше 10 по модулю.

In [8]:
lst = [-11, 2, 4, 13, -20, -5]
def more_than_five(lst):
    new_lst = []
    for number in lst:
        if abs(number) > 10:
            new_lst.append(number)
    return new_lst
print(more_than_five(lst))

[-11, 13, -20]


# Задачи по Numpy

### Задача 1

Создать матрицу размером 10х10 с 0 внутри, и 1 на границах. Например для 3х3.

1 1 1
1 0 1
1 1 1

In [26]:
import numpy as np
x = np.ones((10, 10))
x[1:-1, 1:-1] = 0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### Задача 2

Создать 5x5 матрицу с 1,2,3,4 над диагональю. Все остальные элементы - 0.

In [36]:
import numpy as np
array = np.zeros((5,5))
np.diag([1,2,3,4], k=1)

array([[0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0]])

### Задача 3

Создайте случайную матрицу и вычтите из каждой строки среднее.

In [45]:
import numpy as np
array = np.random.random((5,5))
new_array = array - np.mean(array, axis = 0)
print(new_array)

[[-0.36477088  0.47022593 -0.143192   -0.22075761 -0.16395594]
 [ 0.51398392  0.01822099  0.16242669  0.25298179 -0.07813394]
 [-0.27697431  0.11196511 -0.26541106 -0.15232935 -0.32461562]
 [-0.03025522 -0.18244014  0.40092056 -0.0902415   0.20844557]
 [ 0.15801649 -0.41797189 -0.15474419  0.21034667  0.35825993]]


### Задача 4

Написать функцию, принимающую на вход массив и меняющую знак у элементов, значения которых между 3 и 8. Протестировать на нескольких заданных вами массивах.

In [85]:
import numpy as np
arr = np.arange(10)
arr1 = np.arange(20)
def change_array(arr):
    arr[(3 < arr) & (arr <= 8)] *= -1
    return arr
print(change_array(arr))
print(change_array(arr1))

[ 0  1  2  3 -4 -5 -6 -7 -8  9]
[ 0  1  2  3 -4 -5 -6 -7 -8  9 10 11 12 13 14 15 16 17 18 19]


### Задача 5


Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением.

In [98]:
import numpy as np
vector = np.arange(1,6)
vector2 = np.zeros(len(vector) + (len(vector)-1)*(3))
vector2[::4] = vector
print(vector2)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


### Задача 6


Написать функцию, принимающую на вход матрицу MxN и меняющую 2 любые строки в матрице. Протестировать на нескольких заданных вами примерах.

In [38]:
import numpy as np
M = int(input())
N = int(input())
array = np.random.randint(0, 10, size=(M, N))
array1 = np.random.randint(0, 10, size=(M, N))
print(array)
print(array1)
def change_lines(array):
    print("enter the line numbers you want to swap")
    line1 = int(input())
    line2 = int(input())
    array[line1], array[line2] = array[line2], array[line1].copy()
    return array
print(change_lines(array))
print(change_lines(array1))

3
4
[[6 0 0 0]
 [7 6 9 0]
 [2 8 0 2]]
[[7 0 3 9]
 [8 6 6 1]
 [6 6 2 1]]
enter the line numbers you want to swap
0
1
[[7 6 9 0]
 [6 0 0 0]
 [2 8 0 2]]
enter the line numbers you want to swap
0
1
[[8 6 6 1]
 [7 0 3 9]
 [6 6 2 1]]


### Задача 7

Написать функцию, принимающую на вход одномерный массив и возвращающую наиболее частое значение в массиве и частоту его встречи. Протестировать на нескольких заданных вами примерах.

In [34]:
import numpy as np
array = np.random.randint(0, 10, size=(12))
array1 = np.random.randint(0, 10, size=(15))
print(array, array1)
def frequent_value(array):
    counts = np.bincount(array)
    value = np.argmax(counts)
    count = counts[value]
    return value, count
print(frequent_value(array))
print(frequent_value(array1))

[8 9 7 9 3 9 1 8 7 9 5 0] [4 4 3 8 7 7 4 1 4 9 3 4 8 5 5]
(9, 4)
(4, 5)


### Задача 8

Написать функцию, принимающую на вход массив 16x16 и считающую сумму по блокам 4x4. Протестировать на нескольких заданных вами примерах.

In [49]:
import numpy as np
def summa(array):
    array = np.random.randint(0, 10, size=(16, 16))
    print(array)
    for i in range(0, 16, 4):
            for j in range(0,16,4):
                print('Block 4x4:')
                print(array[i:i+4, j:j+4])
                print('The amount of this block: ',np.sum(array[i:i+4,j:j+4]))
print(summa(array))
print(summa(array1))


[[4 4 1 4 4 7 9 3 1 9 8 7 2 3 3 4]
 [3 2 1 7 6 6 6 6 3 3 5 5 9 9 6 5]
 [3 9 7 3 4 4 0 0 6 5 4 6 8 8 1 0]
 [9 6 7 2 1 0 3 1 2 0 3 5 2 3 9 6]
 [6 1 4 6 9 4 3 3 1 3 2 5 4 8 5 0]
 [0 9 6 1 9 8 7 5 1 4 6 9 6 0 3 4]
 [1 0 3 2 4 2 3 6 3 2 9 1 8 0 4 7]
 [8 3 2 0 2 8 0 9 9 6 8 3 5 0 1 0]
 [3 5 5 7 2 1 4 9 0 1 0 4 7 9 1 2]
 [7 7 1 6 0 7 1 3 8 4 7 1 9 0 1 0]
 [7 3 9 2 4 8 1 5 3 9 4 5 6 7 7 2]
 [8 2 3 4 7 6 7 4 4 6 1 5 5 2 7 9]
 [3 7 6 3 8 6 0 2 9 3 9 3 4 6 2 6]
 [2 9 9 7 5 6 6 8 6 8 4 9 9 8 9 1]
 [8 8 2 7 5 0 0 4 3 6 1 1 6 2 3 0]
 [7 9 6 0 2 1 7 6 0 9 4 2 2 0 2 4]]
Block 4x4:
[[4 4 1 4]
 [3 2 1 7]
 [3 9 7 3]
 [9 6 7 2]]
The amount of this block:  72
Block 4x4:
[[4 7 9 3]
 [6 6 6 6]
 [4 4 0 0]
 [1 0 3 1]]
The amount of this block:  60
Block 4x4:
[[1 9 8 7]
 [3 3 5 5]
 [6 5 4 6]
 [2 0 3 5]]
The amount of this block:  72
Block 4x4:
[[2 3 3 4]
 [9 9 6 5]
 [8 8 1 0]
 [2 3 9 6]]
The amount of this block:  78
Block 4x4:
[[6 1 4 6]
 [0 9 6 1]
 [1 0 3 2]
 [8 3 2 0]]
The amount of this block:  52
Block 4x4

### Задача 9

Написать функцию, принимающую на вход матрицу и возвращающую n наибольших значений в массиве. n вводится с клавиатуры. Протестировать на нескольких заданных вами примерах.

In [40]:
import numpy as np
count_n = int(input())
arr1 = np.random.randint(0, 100, size=(7, 7))
arr2 = np.random.randint(0, 100, size=(4, 4))
print(arr1)
print(arr2)
def max_number(array):
    max_n_numb = np.unique((np.sort(array.flat)))[::-1][:count_n]
    print(count_n,"наибольших значений в матрице")
    return max_n_numb
print(max_number(arr1))
print(max_number(arr2))

4
[[47 18 94 73 81 34 29]
 [98 94 18 60 43  9 64]
 [83 94  4 87 43  2 53]
 [54 46 24  2 99 32 93]
 [45 14 99 78 74 12  7]
 [30 53 29  3 86 90 63]
 [51 34 39 26 41 73 22]]
[[2 1 7 2]
 [8 1 3 1]
 [3 7 7 2]
 [8 5 6 0]]
4 наибольших значений в матрице
[99 98 94 93]
4 наибольших значений в матрице
[8 7 6 5]


### Задача 10

Написать функцию, принимающую на вход 10x3 матрица и находящую строки из неравных значений (например [2,2,3]). Протестировать на нескольких заданных вами примерах.

In [7]:
import numpy as np
def find_line(array):
    array = np.random.randint(0, 7, size=(10, 3))
    print(array)
    line = np.logical_and.reduce(array[:,1:] == array[:,:-1], axis=1)
    return line
print(find_line(array1))
print(find_line(array2))

[[5 1 5]
 [3 1 3]
 [0 1 3]
 [5 1 2]
 [2 4 3]
 [3 4 2]
 [0 4 1]
 [3 4 0]
 [1 1 2]
 [5 6 4]]
[False False False False False False False False False False]
[[3 1 4]
 [0 2 3]
 [6 0 6]
 [1 0 5]
 [1 1 1]
 [0 2 4]
 [1 4 3]
 [4 4 3]
 [3 4 5]
 [6 0 3]]
[False False False False  True False False False False False]


### Задача 11

Написать функцию, принимающую на вход двумерный массив и находящую все различные строки. Протестировать на нескольких заданных вами примерах.

In [59]:
import numpy as np
A = np.array([[1, 1, 0, 1, 1, 1],
            [1, 1, 1, 1, 1, 1],
            [0, 1, 0, 0, 0, 1],
            [1, 0, 1, 0, 1, 1],
            [1, 1, 0, 1, 1, 1],
            [0, 1, 0, 1, 0, 1]])
B = np.array([[1, 2],
            [1, 2],
            [0, 2],
            [3, 4],
            [3, 4]])
def various_lines(array):
    for i in range(len(array)):  # generate pairs
        for j in range(i + 1, len(array)):
            equal_lines = np.array_equal(array[i], array[j])  # compare rows
            if equal_lines == False:
                print("Cтроки под номерами не равны", i,j, "вывод этих строк", array[i], array[j])
print(various_lines(A))
print(various_lines(B))

Cтроки под номерами не равны 0 1 вывод этих строк [1 1 0 1 1 1] [1 1 1 1 1 1]
Cтроки под номерами не равны 0 2 вывод этих строк [1 1 0 1 1 1] [0 1 0 0 0 1]
Cтроки под номерами не равны 0 3 вывод этих строк [1 1 0 1 1 1] [1 0 1 0 1 1]
Cтроки под номерами не равны 0 5 вывод этих строк [1 1 0 1 1 1] [0 1 0 1 0 1]
Cтроки под номерами не равны 1 2 вывод этих строк [1 1 1 1 1 1] [0 1 0 0 0 1]
Cтроки под номерами не равны 1 3 вывод этих строк [1 1 1 1 1 1] [1 0 1 0 1 1]
Cтроки под номерами не равны 1 4 вывод этих строк [1 1 1 1 1 1] [1 1 0 1 1 1]
Cтроки под номерами не равны 1 5 вывод этих строк [1 1 1 1 1 1] [0 1 0 1 0 1]
Cтроки под номерами не равны 2 3 вывод этих строк [0 1 0 0 0 1] [1 0 1 0 1 1]
Cтроки под номерами не равны 2 4 вывод этих строк [0 1 0 0 0 1] [1 1 0 1 1 1]
Cтроки под номерами не равны 2 5 вывод этих строк [0 1 0 0 0 1] [0 1 0 1 0 1]
Cтроки под номерами не равны 3 4 вывод этих строк [1 0 1 0 1 1] [1 1 0 1 1 1]
Cтроки под номерами не равны 3 5 вывод этих строк [1 0 1 0 1 1] 

### Задача 12

Написать функцию, принимающую на вход два вектора одинакого размера и считающую расстояние между векторами. Протестировать на нескольких заданных вами примерах.

In [5]:
import numpy as np
a1 = np.array([1, 2, 3])
b1 = np.array([0, 1, 1])
a2 = np.array([3, 4, 6])
b2 = np.array([5, 6, 7])
def distance(a, b):
    dist = np.linalg.norm(a-b)
    return dist
print(distance(a1, b1))
print(distance(a2, b2))

2.449489742783178
3.0


### Задача 13

Написать функцию, принимающую на вход два вектора одинакого размера и находящую косинус угла между векторами. Протестировать на нескольких заданных вами примерах.

In [11]:
import numpy as np
v1 = np.array([1, 2, 3], float)
v2 = np.array([0, 1, 1], float)
v3 = np.array([4, 5, 6], float)
v4 = np.array([7, 8, 1], float)
def cos_of_angle(vector1, vector2):
    numerator = np.dot(vector1, vector2)
    denominator = np.linalg.norm(vector1) * np.linalg.norm(vector2)
    cosin = numerator/denominator
    return cosin
print(cos_of_angle(v1, v2))
print(cos_of_angle(v3, v4))

0.944911182523068
0.7898305565390809


### Задача 14

Написать функцию, принимающую на вход вектор A содержит float числа как больше, так и меньше нуля.

Функция должна округлить их до целых и результат записать в глобальную переменную Z. Округление должно быть "от нуля", т.е.:

* положительные числа округляем всегда вверх до целого

* отрицательные числа округляем всегда вниз до целого

* 0 остаётся 0

Протестировать на нескольких заданных вами примерах.

In [29]:
Z = []
A = np.array([1.4, 2.7, 3.6, -1.2, -2.0, -3.8, 0])
A1 = np.array([1.1, 2.4, 3.3, -1.8, -2.0, -8.6, 0])
def rounding(vector):
    Z = np.round(vector)
    return Z
print(rounding(A))
print(rounding(A1))

[ 1.  3.  4. -1. -2. -4.  0.]
[ 1.  2.  3. -2. -2. -9.  0.]


### Задача 15

Написать функцию, принимающую на вход 2 вектора целых чисел A и B.

Функция должна находить числа, встречающиеся в обоих векторах и добавлять их по возрастанию в глобальную переменную - вектор Z.

Если пересечений нет, то вектор Z будет пустым.

Протестировать на нескольких заданных вами примерах.

In [48]:
Z = np.array([])
v1 = np.array([14, 2, 88, 9, 3, 2, 10], int)
v2 = np.array([0, 10, 1, 3, 88, 14], int)
v3 = np.array([0, 5, 5, 5, 0, 4], int)
def intersection(vector1, vector2):
    Z = np.intersect1d(vector1, vector2)
    return Z
print(intersection(v1, v2))
print(intersection(v1, v3))

[ 3 10 14 88]
[]


### Задача 16

Написать функцию, принимающую на вход вектор и возвращающую максимальный элемент в векторе среди элементов, перед которыми стоит 0.

Например для:

x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])

Ответ: 5

In [73]:
import numpy as np
v1 = np.array([6, 2, 0, 3, 0, 5, 7, 0])
def max_after_zero(vector):
    zero = vector  == 0
    max_number = vector[1:][zero[:-1]].max()
    return max_number
print(max_after_zero(v1))

5


### Задача 17

Написать функцию, принимающую на вход матрицу 5х3 и считающую длину каждого вектора в матрице (строка) и ищущую самый длинный вектор, вернуть его координаты и длину.

Как выглядит матрица:

     | x | y | z |
     | 1 | 2 | 3 |
     | 3 | 4 | 1 |
     | ...       |

In [101]:
import numpy as np
from math import sqrt
arr = np.array([[1, 2, 3],
            [1, 4, 4],
            [2, 3, 3],
            [4, 5, 5],
            [0, 6, 6]])
arr1 = np.random.randint(0, 10, size=(5, 3))
print(arr)
print(arr1)
def longest_vector(array):
    length0 = 0
    for i in range(0, 5):
        x = array[i][0]
        y = array[i][1]
        z = array[i][2]
        print(x,y,z)
        length = sqrt(x ** 2 + y ** 2 + z ** 2)
        print(length)
        if length > length0:
            length0 = length
            coord = array[i]
    return length0, coord
print(longest_vector(arr))
print(longest_vector(arr1))

[[1 2 3]
 [1 4 4]
 [2 3 3]
 [4 5 5]
 [0 6 6]]
[[2 4 8]
 [6 5 8]
 [7 2 0]
 [9 1 6]
 [3 8 7]]
1 2 3
3.7416573867739413
1 4 4
5.744562646538029
2 3 3
4.69041575982343
4 5 5
8.12403840463596
0 6 6
8.48528137423857
(8.48528137423857, array([0, 6, 6]))
2 4 8
9.16515138991168
6 5 8
11.180339887498949
7 2 0
7.280109889280518
9 1 6
10.862780491200215
3 8 7
11.045361017187261
(11.180339887498949, array([6, 5, 8]))
